### ISSUE TITLE
bind with value doesn't works 

### ISSUE THREAD

**Issue by titou-from-mars** [arabsight/aurelia-quill-plugin#1]
Hi
If you affect a new value to the property bind with quillEditor.value, there is no change in Quill editor. The solution is pretty simple . In [quill-editor.js](https://github.com/arabsight/aurelia-quill-plugin/blob/master/src/quill-editor.js)  add 
```
valueChanged(newValue) {       
      this.editor.root.innerHTML = newValue;
        
} 
```

**Comment by titou-from-mars** [comment]
My bad :
```
valueChanged(newValue) { 
         if(this.editor.root.innerHTML !== newValue) this.editor.root.innerHTML = newValue; 
}
```

**Comment by arabsight** [comment]
Hi, thanks and sorry for the late response, its fixed.
