### ISSUE TITLE
after making entire text as bold, enter key is not working

### ISSUE THREAD

**Issue by webcat12345** [arabsight/aurelia-quill-plugin#4]
### Reproduce step

* Implement editor
* Select entire text and make it bold/italic
* Place cursor at the end of the text and press enter
* Cursor is being moved to the beginning of the text

### Expected behavior

* Just go to next line

### More information which could be helpful

* Even the cursor is not working properly, a new line will be added. I can go to new line with arrow keys/mouse.

**Comment by arabsight** [comment]
fixed in v0.1.6

**Comment by webcat12345** [comment]
all works, thanks
