### ISSUE TITLE
Mutiple controls on form

### ISSUE THREAD

**Issue by johntom** [arabsight/aurelia-quill-plugin#6]
Hi,
In process of converting kendoui rich text controls and in my evaluations I've chosen quill as I think its the best match for my needs.
If I have one control on form I'm able to extract the html with the following code.
```
var delta = $('.ql-editor').html();
delta = <h1>John Doe</h1>
```
1) Is this the most efficient way to get at the html
2) How do I extract the html from another <quill-editor> instance on the same form.
Thanks so much for your efforts and documentation.
John

**Comment by arabsight** [comment]
Hi, its been a long time since I used aurelia.
you can just use the bindable properties (they return html)

```html
<quill-editor value.bind="message"></quill-editor>
<quill-editor value.bind="delta"></quill-editor>
```

```
message:
<p>Hello World!</p> 

delta:
<p>Hello John!</p>
```

**Comment by johntom** [comment]
Thanks, I would sware that I tried that but works as described. So you jumped ship to React?

**Comment by arabsight** [comment]
yeah react and vue
